# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['src/app.py'],
    pathex=['src', 'third_party/teamtalk/tt5sdk_v5.19a_win64/Library/TeamTalkPy'],
    binaries=[],
    datas=[
        ('src/teamtalk_client', 'teamtalk_client'),
        ('src/platform_paths.py', '.'),
        ('src/ui', 'ui'),
        ('src/ui_wx', 'ui_wx'),
        ('src/ui_qt', 'ui_qt'),
        ('src/chat_history.py', '.'),
        ('src/global_hotkeys.py', '.'),
        ('src/screen_capture.py', '.'),
        ('src/system_audio.py', '.'),
        ('licenses', 'licenses'),
        ('CHANGELOG.txt', '.'),
        ('INSTALL_macOS.md', '.'),
        ('src/manual.html', '.'),
        ('third_party/teamtalk/tt5sdk_v5.19a_win64/Library/TeamTalkPy', 'TeamTalkPy'),
        ('third_party/teamtalk/tt5sdk_v5.19a_win64/Library/TeamTalk_DLL', 'TeamTalk_DLL'),
        ('third_party/yt-dlp', 'yt-dlp'),
        ('third_party/espeak-ng', 'espeak-ng'),
        ('src/sounds', 'sounds'),
        ('src/screen_reader.py', '.'),
        ('third_party/tolk', 'tolk'),
    ],
    hiddenimports=[
        'app_qt',
        'screen_reader',
        'teamtalk_client', 'teamtalk_client.tt', 'teamtalk_client.client',
        'ui.tabs.system', 'ui_qt.tabs.system', 'platform_paths', 'sound_manager',
        'chat_history', 'global_hotkeys', 'i18n',
        'mss', 'mss.tools', 'screen_capture', 'system_audio',
        'win32gui', 'win32con',
        'PySide6', 'PySide6.QtWidgets', 'PySide6.QtCore', 'PySide6.QtGui',
        'winsound',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['whisper', 'torch', 'numba', 'numba.core', 'llvmlite',
              'tiktoken', 'tiktoken_ext', 'tiktoken_ext.openai_public',
              'objc', 'AppKit', 'Quartz',
              'wx', 'wx.adv', 'wx.dataview'],
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='TeamTalk VO Client',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='version_info.txt',
    manifest='app.manifest',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='TeamTalk VO Client',
)
